name: conda-environment
channels:
  - bioconda
  - r
#  - conda-forge
dependencies:
  - r=3.6.0
  - freebayes 
  - bowtie2
  - samtools
  - vcflib
  - r-glue
  - r-ape
  - r-dplyr
#  - r-vcfr
#  - r-devtools
  
